---
# ===================================
# Dokploy Infrastructure Variables
# ===================================

# Node.js
node_version: "20"

# Dokploy
dokploy_version: "v0.8.0"
dokploy_port: 3000
dokploy_install_dir: "/opt/dokploy"
dokploy_repo: "https://github.com/Dokploy/dokploy.git"
dokploy_user: "dokploy"
dokploy_group: "dokploy"
dokploy_database_dir: "/opt/dokploy/database"
dokploy_network: "dokploy_net"
